# Generated by Django 4.1.2 on 2022-11-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='accnum',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp856', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.CharField(default='', max_length=16),
        ),
    ]
