# Generated by Django 4.1.2 on 2022-11-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_recruitment_department_alter_employee_emp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='upload_your_cv',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp77119', max_length=70),
        ),
    ]
